# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161006_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checked_out',
            field=models.DateTimeField(null=True),
        ),
    ]
