# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161006_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='check_in',
            field=models.BooleanField(default=True),
        ),
    ]
