# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='check_in',
            field=models.BooleanField(),
        ),
    ]
