# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161007_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checked_out_by',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
