# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_book_checked_out_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='book_author', to='app.Author'),
        ),
    ]
